/**
 * Generated by firestore-odm
 * Do not edit manually.
 *
 * Core runtime library for generated TypeScript code.
 * Contains common types, helpers, or base classes.
 */

// Re-export common Firestore types for convenience
export {
  Firestore,
  CollectionReference,
  DocumentReference,
  Timestamp,
  GeoPoint,
  FieldValue, // Base type for serverTimestamp, increment etc.
  serverTimestamp,
  increment,
  arrayUnion,
  arrayRemove,
  deleteField,
  // Add other exports as needed
} from 'firebase/firestore';

// Example: Base class (optional, can be added later if needed)
// export abstract class FirestoreOdmBase {
//   // Common properties or methods
// }

console.log('Firestore ODM Core Runtime Loaded (Generated)');