name: my_project_firestore_models_dart
description: Generated Dart models for Firestore
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'
  # flutter: '>=1.17.0'

dependencies:
  # flutter:
  #   sdk: flutter
  cloud_firestore: ^5.0.0 # User needs this
  fireschema_dart_runtime: # Depends on the runtime package
    path: ../../packages/fireschema_dart_runtime
  # meta: ^1.8.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.0

