/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import 'package:cloud_firestore/cloud_firestore.dart';
// Runtime Imports
import 'package:fireschema_dart_runtime/fireschema_dart_runtime.dart'; // Import the runtime package

// Local Imports
import 'tags_data.dart';

/// A typed builder for creating update operations for 'tags' documents, extending BaseUpdateBuilder.
class TagsUpdateBuilder extends BaseUpdateBuilder<TagsData> {

  /// Creates a TagsUpdateBuilder instance.
  TagsUpdateBuilder({required DocumentReference<TagsData> docRef})
      : super(docRef: docRef);

  // Constructor and internal updateData map are inherited from BaseUpdateBuilder

  // --- Field Setters ---
  /// Sets the value for the 'label' field.
  TagsUpdateBuilder setLabel(String value) {
    // Call the protected set method from the base class
    return set('label', value) as TagsUpdateBuilder; // Cast back
  }


  // --- End Field Setters ---

  // commit() method is inherited from BaseUpdateBuilder

  // --- Custom Update Methods Placeholder ---
}