/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import 'package:cloud_firestore/cloud_firestore.dart';
// Runtime Imports
import 'package:fireschema_dart_runtime/fireschema_dart_runtime.dart'; // Import the runtime package

// Local Imports
import 'tags_data.dart';

/// A typed query builder for the 'tags' collection, extending BaseQueryBuilder.
class TagsQueryBuilder extends BaseQueryBuilder<TagsData> {

  /// Creates a TagsQueryBuilder instance.
  TagsQueryBuilder({
    required FirebaseFirestore firestore,
    required CollectionReference<TagsData> collectionRef,
  }) : super(firestore: firestore, collectionRef: collectionRef);

  // Constructor and internal query state are inherited from BaseQueryBuilder

  // --- Field-specific Where Methods ---
  /// Adds a query filter for the 'label' field.
  /// Provide one of the named parameters to specify the query condition.
  TagsQueryBuilder whereLabel({
    String? isEqualTo, // Ensure only one trailing '?' for nullable parameter
    String? isNotEqualTo, // Ensure only one trailing '?' for nullable parameter
    String? isLessThan, // Ensure only one trailing '?' for nullable parameter
    String? isLessThanOrEqualTo, // Ensure only one trailing '?' for nullable parameter
    String? isGreaterThan, // Ensure only one trailing '?' for nullable parameter
    String? isGreaterThanOrEqualTo, // Ensure only one trailing '?' for nullable parameter
    List<dynamic>? whereIn, // Ensure only one trailing '?' for nullable parameter
    List<dynamic>? whereNotIn, // Ensure only one trailing '?' for nullable parameter
  }) {
    // Call the protected where method from the base class
    return where(
      'label', // Pass the field path string
      isEqualTo: isEqualTo,
      isNotEqualTo: isNotEqualTo,
      isLessThan: isLessThan,
      isLessThanOrEqualTo: isLessThanOrEqualTo,
      isGreaterThan: isGreaterThan,
      isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
      whereIn: whereIn,
      whereNotIn: whereNotIn,
    ) as TagsQueryBuilder; // Cast back to specific type is necessary
  }
  // --- End Field-specific Where Methods ---

  // Methods like orderBy(), limit(), limitToLast(), startAt(), startAfter(),
  // endBefore(), endAt(), get(), getData() are inherited from BaseQueryBuilder.

  // --- Custom Query Methods Placeholder ---
}