/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import { Timestamp, GeoPoint, DocumentReference, DocumentData } from 'firebase/firestore';













/**
 * Represents the structure of a 'Items' document.
 * Description: A collection of test items.
 */
export interface ItemsData {
  /** name (string, required) */
  name: string;
  /** value (number) */
  value?: number;
  /** createdAt (timestamp, required) */
  createdAt: Timestamp;
  /** address (map) */
  address?: { street: string; city: string; zip?: string; coords?: { lat: number; lon: number } };
}

// Potential future additions:
// - A class wrapper for data with helper methods?
// - Separate types for creation vs reading?