/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import {
  DocumentReference,
  // updateDoc, // Handled by base class commit()
  FieldValue, // Keep for potential direct use if needed, though base provides helpers
  Timestamp,  // Needed for timestamp field setters
  // DocumentReference, // Needed for reference field setters (Already imported above)
  // serverTimestamp, // Handled by base class helper _serverTimestamp()
  // increment, // Handled by base class helper _increment()
  // arrayUnion, // Handled by base class helper _arrayUnion()
  // arrayRemove, // Handled by base class helper _arrayRemove()
  // deleteField, // Handled by base class helper _deleteField()
} from 'firebase/firestore';
// Runtime Imports
import { BaseUpdateBuilder } from '@fireschema/ts-runtime'; // Adjust path/package name as needed

// Local Imports
import { ItemsData } from './items.types.js';











/**
 * A typed builder for creating update operations for 'items' documents, extending BaseUpdateBuilder.
 */
export class ItemsUpdateBuilder extends BaseUpdateBuilder<ItemsData> {

  // Constructor is inherited from BaseUpdateBuilder
  // _docRef and _updateData are managed by the base class

  // --- Field Setters ---
  /** Sets the value for the 'name' field. */
  setName(value: string): this {
    // Call the protected _set method from the base class
    return this._set('name', value);
  }


  /** Sets the value for the 'value' field. */
  setValue(value: number): this {
    // Call the protected _set method from the base class
    return this._set('value', value);
  }

  /** Atomically increments the 'value' field. */
  incrementValue(value: number): this {
    // Call the protected _increment helper (or _set with increment(value))
    return this._increment('value', value);
    // Alternatively: return this._set('value', increment(value));
  }
  /** Deletes the 'value' field. */
  deleteValue(): this {
    // Call the protected _deleteField helper
    return this._deleteField('value');
    // Alternatively: return this._set('value', deleteField());
  }

  /** Sets the value for the 'createdAt' field. */
  setCreatedAt(value: Timestamp): this {
    // Call the protected _set method from the base class
    return this._set('createdAt', value);
  }

  /** Sets the 'createdAt' field to the server timestamp. */
  setCreatedAtToServerTimestamp(): this {
    // Call the protected _serverTimestamp helper
    return this._serverTimestamp('createdAt');
    // Alternatively: return this._set('createdAt', serverTimestamp());
  }

  // --- End Field Setters ---

  // commit() method is inherited from BaseUpdateBuilder

  // --- Custom Update Methods Placeholder ---
  // Example: markAsRead() { return this._set('read', true); }
}