/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import 'package:cloud_firestore/cloud_firestore.dart';
// Runtime Imports
import 'package:fireschema_dart_runtime/fireschema_dart_runtime.dart'; // Import the runtime package

// Local Imports
import 'items_data.dart';

/// A typed builder for creating update operations for 'items' documents, extending BaseUpdateBuilder.
class ItemsUpdateBuilder extends BaseUpdateBuilder<ItemsData> {

  /// Creates a ItemsUpdateBuilder instance.
  ItemsUpdateBuilder({required DocumentReference<ItemsData> docRef})
      : super(docRef: docRef);

  // Constructor and internal updateData map are inherited from BaseUpdateBuilder

  // --- Field Setters ---
  /// Sets the value for the 'name' field.
  ItemsUpdateBuilder setName(String value) {
    // Call the protected set method from the base class
    return set('name', value) as ItemsUpdateBuilder; // Cast back
  }


  /// Sets the value for the 'value' field.
  ItemsUpdateBuilder setValue(num? value) {
    // Call the protected set method from the base class
    return set('value', value) as ItemsUpdateBuilder; // Cast back
  }

  /// Atomically increments the 'value' field by the given value.
  ItemsUpdateBuilder incrementValue(num value) {
    // Call the protected increment helper
    return increment('value', value) as ItemsUpdateBuilder; // Cast back
  }
  /// Deletes the 'value' field.
  ItemsUpdateBuilder deleteValue() {
    // Call the protected deleteField helper
    return deleteField('value') as ItemsUpdateBuilder; // Cast back
  }

  /// Sets the value for the 'createdAt' field.
  ItemsUpdateBuilder setCreatedAt(Timestamp value) {
    // Call the protected set method from the base class
    return set('createdAt', value) as ItemsUpdateBuilder; // Cast back
  }

  /// Sets the 'createdAt' field to the server timestamp.
  ItemsUpdateBuilder setCreatedAtToServerTimestamp() {
    // Call the protected serverTimestamp helper
    return serverTimestamp('createdAt') as ItemsUpdateBuilder; // Cast back
  }

  /// Sets the value for the 'address' field.
  ItemsUpdateBuilder setAddress(Map<String, dynamic>? value) {
    // Call the protected set method from the base class
    return set('address', value) as ItemsUpdateBuilder; // Cast back
  }

  /// Deletes the 'address' field.
  ItemsUpdateBuilder deleteAddress() {
    // Call the protected deleteField helper
    return deleteField('address') as ItemsUpdateBuilder; // Cast back
  }

  // --- End Field Setters ---

  // commit() method is inherited from BaseUpdateBuilder

  // --- Custom Update Methods Placeholder ---
}