/**
 * FireSchema TypeScript Runtime Library
 *
 * Exports base classes and types used by code generated by the FireSchema CLI.
 */

export { BaseCollectionRef, type CollectionSchema, type FieldSchema } from './baseCollection';
// Export generic types (including new Query types)
export type {
    FirestoreLike, CollectionReferenceLike, DocumentReferenceLike, DocumentSnapshotLike,
    SetOptionsLike, TimestampLike, FieldValueLike, DocumentDataLike, GeoPointLike,
    QueryLike, QuerySnapshotLike, WhereFilterOpLike, OrderByDirectionLike // Added WhereFilterOpLike, OrderByDirectionLike
} from './baseCollection';
// Export QueryBuilder types
export { BaseQueryBuilder, type QueryConstraintLike, type QueryConstraintDefinition } from './baseQueryBuilder'; // Removed WhereFilterOpLike, OrderByDirectionLike
export { BaseUpdateBuilder } from './baseUpdateBuilder';

// Re-export common Firestore types for convenience? Optional.
// export {
//   Firestore,
//   CollectionReference,
//   DocumentReference,
//   DocumentSnapshot,
//   QuerySnapshot,
//   Timestamp,
//   FieldValue,
//   serverTimestamp,
//   increment,
//   arrayUnion,
//   arrayRemove,
//   deleteField,
//   type OrderByDirection,
//   type WhereFilterOp,
// } from 'firebase/firestore';