/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import {
  Firestore,
  CollectionReference,
  // Query, // Handled by base class
  // QueryConstraint, // Handled by base class
  // query, // Handled by base class
  // where as firestoreWhere, // Handled by base class _where
  // orderBy, // Handled by base class
  // limit, // Handled by base class
  // getDocs, // Handled by base class get() / getSnapshot()
  // limitToLast, // Handled by base class
  // startAt, // Handled by base class
  // startAfter, // Handled by base class
  // endAt, // Handled by base class
  // endBefore, // Handled by base class
  DocumentSnapshot, // Needed for cursor method signatures in base class
  WhereFilterOp, // Needed for where method signatures
  OrderByDirection, // Needed for orderBy signature in base class
  Timestamp,        // Needed for timestamp field queries
  DocumentReference // Needed for reference field queries
} from 'firebase/firestore';
// Runtime Imports
import { BaseQueryBuilder } from '@shtse8/fireschema-runtime'; // Adjust path/package name as needed

// Local Imports
import { TagsData } from './tags.types.js';







/**
 * A typed query builder for the 'tags' collection, extending BaseQueryBuilder.
 */
export class TagsQueryBuilder extends BaseQueryBuilder<TagsData> {

  // Constructor is inherited from BaseQueryBuilder

  // --- Field-specific Where Methods ---
  // Overloads for 'label' field type safety based on operator
  whereLabel(op: '==', value: string): this;
  whereLabel(op: '!=', value: string): this;
  whereLabel(op: '<', value: string): this;
  whereLabel(op: '<=', value: string): this;
  whereLabel(op: '>', value: string): this;
  whereLabel(op: '>=', value: string): this;
  whereLabel(op: 'in', value: string[]): this;
  whereLabel(op: 'not-in', value: string[]): this;
  // Implementation signature for 'label'
  whereLabel(
    op: WhereFilterOp, // Use WhereFilterOp for implementation signature
    value: any   // Use any for implementation signature
  ): this {
    // Call the protected _where method from the base class
    return this._where('label', op, value);
  }
  // --- End Field-specific Where Methods ---

  // Methods like orderBy(), limit(), limitToLast(), startAt(), startAfter(),
  // endBefore(), endAt(), get(), getSnapshot() are inherited from BaseQueryBuilder.

  // --- Custom Query Methods Placeholder ---
  // Example: findByStatus(status: string) { return this._where('status', '==', status); }
}