/**
 * Generated by firestore-odm
 * Do not edit manually.
 */
import { Timestamp, GeoPoint, DocumentReference, DocumentData } from 'firebase/firestore';







/**
 * Represents the structure of a 'Tags' document.
 * Description: Tags for an item.
 */
export interface TagsData {
  /** label (string, required) */
  label: string;
}

// Potential future additions:
// - A class wrapper for data with helper methods?
// - Separate types for creation vs reading?