name: Publish Packages

on:
  push:
    tags:
      # Must align with the tag-pattern configured on pub.dev
      - 'v[0-9]+.[0-9]+.[0-9]+' # Example for tag pattern 'v{{version}}' on pub.dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build all packages
        run: bun run build

      - name: Run tests
        run: bun run test

  publish-npm:
    needs: build-and-test # Run after build and test succeed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build all packages # Build again in this job context
        run: bun run build

      - name: Set up Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a version compatible with your project/npm
          registry-url: 'https://registry.npmjs.org'

      - name: Publish @fireschema/ts-runtime to npm
        run: cd packages/fireschema-ts-runtime && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish fireschema CLI to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Publish Dart package using the official reusable workflow (OIDC)
  publish-dart:
    needs: build-and-test
    permissions: # Permissions needed for OIDC
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1 # Call the reusable workflow
    with: # Pass inputs to the reusable workflow
      working-directory: ./packages/fireschema_dart_runtime
      # If you configure a GitHub Environment called 'pub.dev' for added protection:
      # environment: pub.dev
      # environment: pub.dev