name: Main CI (CLI Build & Test)

on:
  push:
    branches:
      - main # Trigger on pushes to main
  pull_request: # Also trigger on PRs

jobs:
  build-and-test-cli: # Renamed job for clarity
    name: Build & Test CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Checkout submodules

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Root Dependencies # Install only root deps
        run: bun install --frozen-lockfile

      # Build only the root package (CLI)
      # Assuming build:root handles this
      - name: Build CLI Package
        run: bun run build:root

      # --- Testing (Optional - depends if root has tests) ---
      # If the root package has tests that DON'T depend on emulator/runtimes:
      # - name: Run Root Tests (if any)
      #   run: bun run test:root # Assuming a separate test script exists

      # --- Docs Build (Keep this here) ---
      - name: Build VitePress site
        run: bun run docs:build # Use bun

      - name: Upload VitePress build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./docs

  # --- Deployment Job (Keep this here) ---
  deploy-docs:
    needs: build-and-test-cli # Depends on the CLI build job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download VitePress build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # Keep existing user config or remove if default is fine
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'

# Removed publish-npm and publish-dart jobs.
# These should live in the respective runtime package repositories.